version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres:/usr/local/var/postgres/data
    ports:
      - "5432:5432"

  redis:
    image: 'redis'
    command: redis-server
    volumes:
      - 'redis:/usr/local/etc/data'
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: ./docker/app/DockerFile
    environment:
      RAILS_ENV: $RAILS_ENV
      REDIS_URL: $REDIS_URL
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"

  sidekiq:
    build:
      context: .
      dockerfile: ./docker/app/DockerFile
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: $RAILS_ENV
      REDIS_URL: $REDIS_URL
    depends_on:
      - db
      - redis
    volumes:
      - '.:/app'

  web:
    build:
      context: .
      dockerfile: ./docker/web/DockerFile
    depends_on:
      - app
    ports:
      - "80:80"

volumes:
  postgres:
  redis:
