require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Api::V1::ThermoStatsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ThermoStat. As you add validations to ThermoStat, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {location: "Chennai, India"}
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ThermoStatsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all thermo_stats as @thermo_stats" do
      process :index, method: :get
      assert_response :ok
      # process :create, method: :post,
      # params: {
      #   valid_attributes
      # }
      # get :index, {}, valid_session
      # expect(assigns(:thermo_stats)).to eq([thermo_stat])
    end
  end

  # describe "GET show" do
  #   it "assigns the requested thermo_stat as @thermo_stat" do
  #     thermo_stat = ThermoStat.create! valid_attributes
  #     get :show, {:id => thermo_stat.to_param}, valid_session
  #     expect(assigns(:thermo_stat)).to eq(thermo_stat)
  #   end
  # end

  # describe "GET new" do
  #   it "assigns a new thermo_stat as @thermo_stat" do
  #     get :new, {}, valid_session
  #     expect(assigns(:thermo_stat)).to be_a_new(ThermoStat)
  #   end
  # end

  # describe "GET edit" do
  #   it "assigns the requested thermo_stat as @thermo_stat" do
  #     thermo_stat = ThermoStat.create! valid_attributes
  #     get :edit, {:id => thermo_stat.to_param}, valid_session
  #     expect(assigns(:thermo_stat)).to eq(thermo_stat)
  #   end
  # end

  # describe "POST create" do
  #   describe "with valid params" do
  #     it "creates a new ThermoStat" do
  #       expect {
  #         post :create, {:thermo_stat => valid_attributes}, valid_session
  #       }.to change(ThermoStat, :count).by(1)
  #     end

  #     it "assigns a newly created thermo_stat as @thermo_stat" do
  #       post :create, {:thermo_stat => valid_attributes}, valid_session
  #       expect(assigns(:thermo_stat)).to be_a(ThermoStat)
  #       expect(assigns(:thermo_stat)).to be_persisted
  #     end

  #     it "redirects to the created thermo_stat" do
  #       post :create, {:thermo_stat => valid_attributes}, valid_session
  #       expect(response).to redirect_to(ThermoStat.last)
  #     end
  #   end

  #   describe "with invalid params" do
  #     it "assigns a newly created but unsaved thermo_stat as @thermo_stat" do
  #       post :create, {:thermo_stat => invalid_attributes}, valid_session
  #       expect(assigns(:thermo_stat)).to be_a_new(ThermoStat)
  #     end

  #     it "re-renders the 'new' template" do
  #       post :create, {:thermo_stat => invalid_attributes}, valid_session
  #       expect(response).to render_template("new")
  #     end
  #   end
  # end

  # describe "PUT update" do
  #   describe "with valid params" do
  #     let(:new_attributes) {
  #       skip("Add a hash of attributes valid for your model")
  #     }

  #     it "updates the requested thermo_stat" do
  #       thermo_stat = ThermoStat.create! valid_attributes
  #       put :update, {:id => thermo_stat.to_param, :thermo_stat => new_attributes}, valid_session
  #       thermo_stat.reload
  #       skip("Add assertions for updated state")
  #     end

  #     it "assigns the requested thermo_stat as @thermo_stat" do
  #       thermo_stat = ThermoStat.create! valid_attributes
  #       put :update, {:id => thermo_stat.to_param, :thermo_stat => valid_attributes}, valid_session
  #       expect(assigns(:thermo_stat)).to eq(thermo_stat)
  #     end

  #     it "redirects to the thermo_stat" do
  #       thermo_stat = ThermoStat.create! valid_attributes
  #       put :update, {:id => thermo_stat.to_param, :thermo_stat => valid_attributes}, valid_session
  #       expect(response).to redirect_to(thermo_stat)
  #     end
  #   end

  #   describe "with invalid params" do
  #     it "assigns the thermo_stat as @thermo_stat" do
  #       thermo_stat = ThermoStat.create! valid_attributes
  #       put :update, {:id => thermo_stat.to_param, :thermo_stat => invalid_attributes}, valid_session
  #       expect(assigns(:thermo_stat)).to eq(thermo_stat)
  #     end

  #     it "re-renders the 'edit' template" do
  #       thermo_stat = ThermoStat.create! valid_attributes
  #       put :update, {:id => thermo_stat.to_param, :thermo_stat => invalid_attributes}, valid_session
  #       expect(response).to render_template("edit")
  #     end
  #   end
  # end

  # describe "DELETE destroy" do
  #   it "destroys the requested thermo_stat" do
  #     thermo_stat = ThermoStat.create! valid_attributes
  #     expect {
  #       delete :destroy, {:id => thermo_stat.to_param}, valid_session
  #     }.to change(ThermoStat, :count).by(-1)
  #   end

  #   it "redirects to the thermo_stats list" do
  #     thermo_stat = ThermoStat.create! valid_attributes
  #     delete :destroy, {:id => thermo_stat.to_param}, valid_session
  #     expect(response).to redirect_to(thermo_stats_url)
  #   end
  # end

end
