# Postgresql version 3.x
#   gem install pg -v 1.1.3
#
#   Ensure the pg gem is defined in your Gemfile
#   gem 'pg', '~> 1.1.3'
#
default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: iot_thermostat_dev

test:
  <<: *default
  database: iot_thermostat_test

production:
  <<: *default
  database: iot_thermostat_prod